"""empty message

Revision ID: 8ba9e267277a
Revises: 93671431113a
Create Date: 2023-11-18 01:03:41.376814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba9e267277a'
down_revision = '93671431113a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('place_name', sa.String(length=200), nullable=True),
    sa.Column('stay', sa.String(length=200), nullable=True),
    sa.Column('food_drinks', sa.String(length=200), nullable=True),
    sa.Column('activities', sa.String(length=200), nullable=True),
    sa.Column('transportation', sa.String(length=200), nullable=True),
    sa.Column('tips', sa.String(), nullable=True),
    sa.Column('media_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('modified_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
